task:
  name: "ionic_dielectric"
  target_key: "e_ionic"
  friendly_name: "Ionic Dielectric (ε ionic)"

data:
  json_path: "mp_materials.json"
  split_file: "data/splits/split_ionic_dielectric.json"
  feature_file: "data/processed/matminer_features.parquet"
